### PR TITLE
Google Cloud Storage support

### PR DESCRIPTION
**Pull request by bova82**
Added Google Cloud storage support including, as for Amazon S3, bucket size (if gsutil is present).

### CODE REVIEW

**Comment by zertrin** [comment]
Thanks, I've merged it in master but couldn't test it. 

I took this opportunity to change the semantics of my master branch. Instead of being the "stable" branch, it's now the development branch, and have created a dedicated stable branch that will advance more slowly after new changes have been tested for some time.

I'll keep the dev branch for experimental changes.

**Comment by bova82** [comment]
Thank you for the great script.
I think that I made a mistake in README.md. The dependencies "boto" and
"gsutils" are shown both in the main requirement list that in Google Cloud
Storage sub-list. I think that they must be removed from the main section,
because they are needed for Google Cloud Storage only.
Can you change it? If you prefer I can do another pull request.

Giovanni



Il giorno ven 15 mag 2015 alle ore 10:10 zertrin <notifications@github.com>
ha scritto:

**Comment by zertrin** [comment]
I already fixed that in my next commit after the merge ;)

**Comment by bova82** [comment]
Sorry, I missed that. Thanks again!

Il giorno ven 15 mag 2015 alle ore 10:24 zertrin <notifications@github.com>
ha scritto:

**Pull request merged**
