### PR TITLE
Master, Extended mailx options

### PR DESCRIPTION
**Pull request by f-andrey**
Mailx support many extended options, this patch allow use this.

### CODE REVIEW

**Comment by zertrin** [comment]
Hi @f-andrey !

Thanks for this pull request.

Since I did a full rewrite of the section handling email since you did your commits, please rebase your changes on top of current `dev` and redo a pull request without merge conflicts.

**Comment by f-andrey** [comment]
Probably really I missed some of your edits is long time with pull request after local changes.
Now look no conflicts.

**Comment by f-andrey** [comment]
Sorry, this change need more tests.
`${MAILX_OPTIONS} ` - work fine
`"${MAILX_OPTIONS}"` - not work, error mailx options, need search fix expansion variables with bash

**Comment by zertrin** [comment]
Yeah in fact the version without quotes would have been ok in this special case, because you really want to expand the individual arguments.

I'll take care of fixing the test in this case.

**Comment by zertrin** [comment]
After reading https://github.com/koalaman/shellcheck/wiki/SC2086, especially the _"Exceptions"_ section, I've implemented it (hopefully correctly) in pull request #127. 

But I didn't test it yet... Maybe you could test it before I merge it?

Thanks again for suggesting the change. 

In the future however, please use topic branches for your pull requests, and as stated in the README.md section _Contributing_, please branch off from the `dev` branch and not the `master` branch.

**Comment by f-andrey** [comment]
I'm use ansible role for install and she used master branch. As in the DEV is heavily redesigned, until I decided to limit the correction in master.
Maybe later I will examine the transition to DEV, as well as adding support for it postfix (default for RedHat derivatives)

**Comment by zertrin** [comment]
Will close this as I am about to put this project in unmaintained mode in the near future.

Thanks though!

**Pull request closed without merging**
