### PR TITLE
Add IFTTT notification service

### PR DESCRIPTION
**Pull request by jrbenito**
Add the ability to trigger a custom event on the Maker channel provided
by IFTTT service. With this trigger one can program actions on another
channels. Examples:

- Log backup notification to a google spreadsheet;
- Receive notification on devices with IFTTT application installed;
- Send e-mails
- Log to evernote
- Turn a Philips Hue light green for good backup or red on errors

IFTTT Maker channel accepts three values (named `value1`, `value2`, `value3`)
as part of the trigger. This implementation sends the content of
`NOTIFICATION_CONTENT` as `value1` parameter and let `value2` be defined at
configuration file. At this time `value3` is not used.

### CODE REVIEW

**Comment by jrbenito** [comment]
Errors pointed by travis-ci are inherited from `dev` branch. None where pointed at lines this patch introduces.

**Comment by jrbenito** [comment]
Travis-ci is now failing but not on lines this patch introduces.  I dig travis-ci logs and found that now they are using `shellcheck` package version 0.4.4-2, however, last build on `dev` branch used package version 0.3.7-5. 

I believe new checks introduced by new version of `shellcheck` is now triggering errors on the script. However, this was not caused by this patch.

**Comment by zertrin** [comment]
Thanks for this contribution, and thanks for the heads-up about Travis and shellcheck. I'm looking into it right now.

It's a detail, but the echo after the curl is not perfectly indented, could you fix it before I merge?

**Comment by zertrin** [comment]
Thanks again!

**Comment by jrbenito** [comment]
@zertrin ,

Done, it was caused by wrong configuration in my editor. Sorry.
I also upmerged branch against your dev.

**Comment by jrbenito** [comment]
Thanks!

**Pull request merged**
