### PR TITLE
use tee for logging to logfile and stdout

### PR DESCRIPTION
**Pull request by mindrunner**
I need both, logfile and stdout, to see whats happening while the backup is running. Thus, I use tee to copy stdout into a file. Don't know if this is always useful. Maybe we can make this optional?

Furthermore, the duplicity_cleanup_failed() method did not not work for unencrypted backups.

### CODE REVIEW

**Comment by zertrin** [comment]
Thanks and sorry for the delay. I was unavailable at the time of submission and since then I forgot about it.

**Comment by zertrin** [comment]
I was about to merge it, when I thought about the fact that people are currently expecting the script not to output anything as long as nothing is wrong. This can be important for example depending on how your cron-job is defined (stdout output could lead to an email being sent by cron even if everything went well).

I think we need to make it optional (opt-in) in order to avoid breaking backward compatibility. Not sure yet how to do it elegantly. I'm open to ideas.

**Comment by zertrin** [comment]
I've found this StackOverflow with interesting ideas: http://superuser.com/questions/86915/force-bash-script-to-use-tee-without-piping-from-the-command-line

But it's time to sleep, so I'll evaluate how to proceed later ;)

**Comment by mindrunner** [comment]
Cool, thanks for having a look. I was thinking about the same. (Making the logging optional). Had no time yet, tho. Will be on vacation next week and have another look on it afterwards!

Cheers

**Comment by zertrin** [comment]
Hi I'm back with a first attempt at a solution. It's kind of tricky but finally I implemented a variant of the link I found above. See PR #137.

Do you think you could test?

The new behavior is to output all relevant information by default (and log at the same time). For those who don't want output, there is a new option `--quiet` or `-q` that mutes all messages except errors and messages intended for interactive use.

I've tested a bit on my side but since that's quite a big refactoring, I'd appreciate if someone else gives a try before I merge into `dev`.

**Comment by zertrin** [comment]
Hi, I've finally merged my PR #137 into `dev` since it seem to be working, at least for me.

I will close your PR since I solved the issue another way. But I'd love to hear your feedback, and if my solution fit your needs. Don't hesitate to answer here.

**Comment by mindrunner** [comment]
Back from vacation. Will check your solution as soon as I have time for it. Will come back with feedback then. Looks good though! Nice work!

**Pull request closed without merging**
